import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster
          position="top-right"
          toastOptions={{
            success: {
              style: {
                background: 'rgb(5, 46, 22)',
                color: 'white',
                borderRadius: '8px',
              },
              duration: 3000,
            },
            error: {
              style: {
                background: 'rgb(45, 12, 12)',
                color: 'white',
                borderRadius: '8px',
              },
              duration: 5000,
            },
            style: {
              maxWidth: '500px',
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
